export const yojnaCategories = [
  {
    title: 'Health, Nutrition & Wellness',
    slug: 'health-nutrition-wellness',
    description: 'Healthcare, nutrition, wellness, safety, and emergency response initiatives.',
    icon: 'heart-pulse',
    color: 'primary',
    schemes: [
      'Zindagi Muskuraayegi',
      'Dhadkan',
      'Jeevan',
      'Pulse',
      'Golden Hour',
      'Water to All',
      'Project Lifestyle',
      'Project Chhaav',
      'MediGuru',
      'Red Cross',
      'Project Shay Mitra',
      'Project Distri',
      'Raksha',
      'Suraksha',
    ],
  },
  {
    title: 'Education, Skill & Youth',
    slug: 'education-skill-youth',
    description: 'Learning, career guidance, youth development, and skill-building programs.',
    icon: 'graduation-cap',
    color: 'education',
    schemes: [
      'Smriti Pustakalaya',
      'Daksh',
      'Project Utkarsh',
      'Padhega Raipur Badhega Raipur',
      'Project Yuva 2.0',
      'Harihar Pathshala',
      'Career Guru',
      'Project Anubhav',
      'Tejas',
      'Project G2',
      'Know Your Army',
      'Project Antariksh',
      'Pai Pai',
      'Aao Saksham Bane',
    ],
  },
  {
    title: 'Women Empowerment & Livelihood',
    slug: 'women-empowerment-livelihood',
    description: 'Livelihood, entrepreneurship, and financial inclusion initiatives for women.',
    icon: 'users',
    color: 'women',
    schemes: [
      'Khana Khazana',
      'Hunar',
      'Business Didi',
      'Jhariya',
      'Trash to Cash',
      'Pink Didi',
      'Lakhpati Didi',
    ],
  },
  {
    title: 'Agriculture, Development & Environment',
    slug: 'agriculture-development-environment',
    description: 'Village development, agriculture, sanitation, greening, and environment programs.',
    icon: 'leaf',
    color: 'agriculture',
    schemes: [
      'Mera Gaon Meri Pehchan',
      'Clean',
      'Urvi',
      'Green Palna Yojana',
      'Har Ghar Munga',
      'Project Nirman',
      'Project Nano',
      'Project Amrit',
    ],
  },
  {
    title: 'Governance & Service Delivery',
    slug: 'governance-service-delivery',
    description: 'Citizen services, administration, helpdesk, and delivery improvement initiatives.',
    icon: 'landmark',
    color: 'governance',
    schemes: [
      'Aao Khud Ko Parkhein',
      'Alert',
      'Dastavez',
      'Shreshth',
      'Project SARAL',
      'Project Handy',
      'Jandarshan',
      'Call Centre',
      'BPO',
      'Project Susashan Rath',
      'Project sugaam',
      'Team Prahari',
      'Sampoorna',
    ],
  },
  {
    title: 'Social Welfare & Community',
    slug: 'social-welfare-community',
    description: 'Community welfare, inclusion, relief, accessibility, and public support schemes.',
    icon: 'handshake',
    color: 'welfare',
    schemes: [
      'Samadhan',
      'Aangan',
      'Mission 45',
      'Project Sahara',
      'Project Udgosh',
      'Project Divyadhun',
      'Vijayi Bhav',
      'Project Dhwani',
      'Aao Baante Khushiyan',
      'Rahat',
      'Project Maa',
      'Project Badlaav',
      'Project Sukaniya',
      'Project mukti',
      'Project Traffic Warden',
    ],
  },
  {
    title: 'Child Development',
    slug: 'child-development',
    description: 'Child growth, early education, protection, and family support initiatives.',
    icon: 'baby',
    color: 'child',
    schemes: ['Chhuk Chhuk', 'U Shape', 'Chiranjeevi', 'Project Noni'],
  },
  {
    title: 'Tourism, Culture & Startups',
    slug: 'tourism-culture-startups',
    description: 'Culture, heritage, sports, tourism, innovation, and startup-facing initiatives.',
    icon: 'palette',
    color: 'culture',
    schemes: [
      'Dadhichi',
      'Ghanti',
      'Virasat',
      'Global Gaon',
      'Kala Kendra',
      'Sanskriti',
      'Samvidhan Park',
      'Project Aao khel Khele',
      'Innovate',
      'Arambh',
    ],
  },
] as const
